spring:
  application:
    name: task-management-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: postgres
    password: password
  liquibase:
    change-log: classpath:db/changelog-master.yaml
    liquibase-schema: public
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: tasks_schema
  Jackson:
    mapper:
      sort-properties-alphabetically: true
    serialization:
      order-map-entries-by-keys: true
      INDENT_OUTPUT: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
    default-leniency: true
  output:
    ansi:
      enabled: ALWAYS
  banner:
    location: classpath:banner.txt

server:
  port: 8082

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
    enabled: true
    version: openapi_3_1
  show-actuator: false
  use-management-port: false
  override-with-generic-response: false

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.springframework.boot.autoconfigure: WARN
    org.springframework.boot: WARN
    org.springframework.data: WARN
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.hibernate: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc: INFO
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%thread]){faint} %clr([%X{traceId}]){faint} %clr(%logger{36}){cyan}:%clr(%L){faint} - %msg%n%wEx'

services:
  user-mgmt:
    base-url: http://localhost:8081
